package com.myteam.barcellona20180115;

import org.kie.dmn.feel.lang.FEELProperty;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ApplicantData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer age;
	@org.kie.api.definition.type.Label("Marital Status")
	private java.lang.String maritalStatus;
	@org.kie.api.definition.type.Label("Employment Status")
	private java.lang.String employmentStatus;
	@org.kie.api.definition.type.Label("Existing Customer")
	private java.lang.Boolean existingCustomer;
	private Monthly monthly;

	public ApplicantData() {
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

    @FEELProperty("Marital Status")
	public java.lang.String getMaritalStatus() {
		return this.maritalStatus;
	}

	public void setMaritalStatus(java.lang.String maritalStatus) {
		this.maritalStatus = maritalStatus;
	}

    @FEELProperty("Employment Status")
	public java.lang.String getEmploymentStatus() {
		return this.employmentStatus;
	}

	public void setEmploymentStatus(java.lang.String employmentStatus) {
		this.employmentStatus = employmentStatus;
	}

    @FEELProperty("Existing Customer")
	public java.lang.Boolean getExistingCustomer() {
		return this.existingCustomer;
	}

	public void setExistingCustomer(java.lang.Boolean existingCustomer) {
		this.existingCustomer = existingCustomer;
	}

    public com.myteam.barcellona20180115.Monthly getMonthly() {
		return this.monthly;
	}

    public void setMonthly(com.myteam.barcellona20180115.Monthly monthly) {
		this.monthly = monthly;
	}

	public ApplicantData(java.lang.Integer age, java.lang.String maritalStatus,
			java.lang.String employmentStatus,
			java.lang.Boolean existingCustomer,
			com.myteam.barcellona20180115.Monthly monthly) {
		this.age = age;
		this.maritalStatus = maritalStatus;
		this.employmentStatus = employmentStatus;
		this.existingCustomer = existingCustomer;
		this.monthly = monthly;
	}

    @Override
    public String toString() {
        return "ApplicantData [age=" + age + ", maritalStatus=" + maritalStatus + ", employmentStatus=" + employmentStatus + ", existingCustomer=" + existingCustomer + ", monthly=" + monthly + "]";
    }

}