package com.myteam.barcellona20180115;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CreditScore implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.math.BigDecimal FICO;

	public CreditScore() {
	}

	public java.math.BigDecimal getFICO() {
		return this.FICO;
	}

	public void setFICO(java.math.BigDecimal FICO) {
		this.FICO = FICO;
	}

	public CreditScore(java.math.BigDecimal FICO) {
		this.FICO = FICO;
	}

    @Override
    public String toString() {
        return "CreditScore [FICO=" + FICO + "]";
    }

}