package com.myteam.barcellona20180115;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Demo1Event implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Demo1Event() {
    }




}