package com.myteam.barcellona20180115;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RequestedProduct implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String type;
	private java.math.BigDecimal rate;
	private java.math.BigDecimal term;
	private java.math.BigDecimal amount;

	public RequestedProduct() {
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.math.BigDecimal getRate() {
		return this.rate;
	}

	public void setRate(java.math.BigDecimal rate) {
		this.rate = rate;
	}

	public java.math.BigDecimal getTerm() {
		return this.term;
	}

	public void setTerm(java.math.BigDecimal term) {
		this.term = term;
	}

	public java.math.BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(java.math.BigDecimal amount) {
		this.amount = amount;
	}

	public RequestedProduct(java.lang.String type, java.math.BigDecimal rate,
			java.math.BigDecimal term, java.math.BigDecimal amount) {
		this.type = type;
		this.rate = rate;
		this.term = term;
		this.amount = amount;
	}

    @Override
    public String toString() {
        return "RequestedProduct [type=" + type + ", rate=" + rate + ", term=" + term + ", amount=" + amount + "]";
    }

}